/**
 * AlertBadges — Reusable badge/tag components for Alerts & Investigations.
 * SeverityBadge, StatusBadge, ProvenanceBadge, MechanismTag
 */
import React from 'react';

export function SeverityBadge({ severity }) {
  const s = (severity || '').toUpperCase();
  const cls =
    s === 'EXTREME'
      ? 'bg-red-600 text-white border-red-700'
      : s === 'SEVERE'
      ? 'bg-orange-500 text-white border-orange-600'
      : s === 'MODERATE'
      ? 'bg-amber-500 text-white border-amber-600'
      : 'bg-[#5E82A6] text-white border-[#5E82A6]';

  return (
    <span
      className={`px-2 py-0.5 rounded text-[9px] font-bold border font-mono shrink-0 ${cls}`}
    >
      {s || 'UNKNOWN'}
    </span>
  );
}

export function StatusBadge({ status }) {
  const s = (status || 'ACTIVE').toUpperCase();
  const cls =
    s === 'ACTIVE'
      ? 'bg-red-100 text-red-700 border-red-200'
      : s === 'ACKNOWLEDGED'
      ? 'bg-amber-100 text-amber-700 border-amber-200'
      : s === 'RESOLVED'
      ? 'bg-emerald-100 text-emerald-700 border-emerald-200'
      : 'bg-[#EEF6FB] text-[#5E82A6] border-[#D0E3F0]';

  const dot =
    s === 'ACTIVE' ? '●' : s === 'ACKNOWLEDGED' ? '◑' : '○';

  return (
    <span
      className={`px-2 py-0.5 rounded text-[9px] font-bold border font-mono flex items-center gap-1 shrink-0 ${cls}`}
    >
      <span className="text-[8px]">{dot}</span>
      {s}
    </span>
  );
}

/**
 * ProvenanceBadge — shows REAL / ARCHIVE / SYNTHETIC / SYNTHETIC_FALLBACK / MOCK/DEMO
 * Never implies a synthetic alert is a real-world warning.
 */
export function ProvenanceBadge({ mode }) {
  const m = (mode || 'UNKNOWN').toUpperCase();
  const isReal = m === 'REAL';
  const isSynth = m.includes('SYNTHETIC') || m.includes('MOCK') || m.includes('DEMO');
  const isArchive = m === 'ARCHIVE';

  const cls = isReal
    ? 'bg-emerald-100 text-emerald-800 border-emerald-300'
    : isSynth
    ? 'bg-purple-100 text-purple-700 border-purple-200'
    : isArchive
    ? 'bg-blue-100 text-blue-700 border-blue-200'
    : 'bg-[#EEF6FB] text-[#5E82A6] border-[#D0E3F0]';

  const prefix = isReal ? '✓ REAL' : isSynth ? '⚠ ' + m : isArchive ? '📂 ' + m : m;

  return (
    <span
      title={
        isSynth
          ? 'This alert was generated from synthetic/demo data. It does NOT represent a real-world warning.'
          : isReal
          ? 'Generated from real observed sensor data.'
          : undefined
      }
      className={`px-2 py-0.5 rounded text-[9px] font-bold border font-mono ${cls}`}
    >
      {prefix}
    </span>
  );
}

/**
 * MechanismTag — Rule-based vs Model-derived vs Synthetic-demo
 */
export function MechanismTag({ mechanism }) {
  const m = (mechanism || '').toUpperCase();
  const isRule = m.includes('RULE');
  const isModel = m.includes('MODEL');
  const isSynth = m.includes('SYNTHETIC');

  const label = isRule ? 'RULE-BASED' : isModel ? 'MODEL-DERIVED' : isSynth ? 'SYNTHETIC/DEMO' : m;
  const cls = isRule
    ? 'bg-sky-100 text-sky-700 border-sky-200'
    : isModel
    ? 'bg-indigo-100 text-indigo-700 border-indigo-200'
    : isSynth
    ? 'bg-purple-100 text-purple-700 border-purple-200'
    : 'bg-[#EEF6FB] text-[#5E82A6] border-[#D0E3F0]';

  return (
    <span
      title={
        isSynth
          ? 'Generated from synthetic demonstration data — not a real operational warning.'
          : isRule
          ? 'Generated by rule-based thresholds applied to observed/model data.'
          : isModel
          ? 'Generated by the ConvLSTM AI model prediction.'
          : undefined
      }
      className={`px-2 py-0.5 rounded text-[9px] font-bold border font-mono ${cls}`}
    >
      {label}
    </span>
  );
}
